apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${APP_NAME}
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - command:
            - java
            - '-javaagent:/mnt/sw-agent/skywalking-agent.jar'
            - '-Dskywalking.agent.service_name=${SERVICE_NAME}-${NAMESPACE}'
            - '-Dskywalking.collector.backend_service=192.168.50.112:11800'
            - '-jar'
            - /system-service.jar
          args:
            - '--spring.profiles.active=${PROFILE}'
            - '--spring.cloud.nacos.discovery.namespace=${NAMESPACE}'
            - '--spring.cloud.nacos.config.namespace=${NAMESPACE}'
          image: >-
            ${IMAGE}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1

          readinessProbe:
            failureThreshold: 100
            httpGet:
              path: /actuator
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 100
            httpGet:
              path: /actuator
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1

          name: ${APP_NAME}
          volumeMounts:
            - mountPath: /etc/localtime
              name: volume-localtime
            - mountPath: /mnt/ehs-mysql-backup
              name: ehs-mysql-backup
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: volume-localtime
        - hostPath:
            path: /nfs/ehs-mysql-backup-${NAMESPACE}
            type: Directory
          name: ehs-mysql-backup
